USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=yo
REVERSE_DOMAIN=com.sheagcraig
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
PACKAGE_VERSION=2.0.1
PAYLOAD=\
		pack-utilities-yo.app \
		pack-usr-local-bin-yo_scheduler.py \
		pack-Library-LaunchAgents-com.sheagcraig.yo.on_demand.plist \
		pack-Library-LaunchAgents-com.sheagcraig.yo.login_once.plist \
		pack-script-postinstall \
		pack-script-preinstall